server:
  port: 8081
app:
  config:
    name: USER-SERVICE
    version: 1.0
spring:
  application:
    name: user-service
  boot:
    admin:
      client:
        url: http://localhost:1111/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8999/eureka/
